import { useCallback, useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { Activity, ArrowDownToLine, ArrowLeft, ArrowRight, BarChart3, Check, ChevronRight, CircleHelp, Clock3, ExternalLink, FileText, Filter, LayoutDashboard, Menu, Moon, Plus, Search, Settings2, Sun, X } from 'lucide-react';
import { getCategories, getReport, getReports, getRun, getRuns, startRun } from './api.js';
import { Categories, Candidates, NotFound, StyleGuide } from './ExtraPages.jsx';

const stages = ['collect','score','select','research_a','research_b','screenshots','compare','write','render'];
const titleStage = (value='') => value.replaceAll('_',' ').replace(/\b\w/g, m => m.toUpperCase());
const dateLabel = value => value ? new Date(value).toLocaleString([], { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }) : 'Not started';
const errText = e => e?.message || 'The request could not be completed.';

function useData(load, deps=[]) {
  const [state,setState]=useState({loading:true,error:'',data:null});
  const reload=useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{setState({loading:false,error:'',data:await load()})}catch(e){setState({loading:false,error:errText(e),data:null})}},deps);
  useEffect(()=>{reload()},[reload]); return {...state,reload};
}

export default function App(){
  const [toast,setToast]=useState(''); const [menuOpen,setMenuOpen]=useState(false); const [theme,setTheme]=useState(()=>localStorage.getItem('compare-theme')||'light'); const location=useLocation();
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('compare-theme',theme)},[theme]);
  useEffect(()=>{setMenuOpen(false)},[location.pathname]);
  const notify=message=>{setToast(message);window.clearTimeout(window.__compareToast);window.__compareToast=window.setTimeout(()=>setToast(''),3400)};
  return <div className="app-shell"><aside className={`sidebar ${menuOpen?'sidebar-open':''}`}><div className="side-brand"><div className="brand-mark"><BarChart3 size={19}/></div><span>Compare<span className="brand-dot">.</span><small>RESEARCH WORKSPACE</small></span><button className="icon-btn mobile-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu"><X size={18}/></button></div><div className="workspace-label">WORKSPACE</div><nav className="side-nav" aria-label="Main navigation">
    <NavLink end to="/" className={({isActive})=>isActive?'nav-item active':'nav-item'}><LayoutDashboard size={17}/> Overview</NavLink><NavLink to="/app/reports" className={({isActive})=>isActive?'nav-item active':'nav-item'}><FileText size={17}/> Reports</NavLink><NavLink to="/app/runs" className={({isActive})=>isActive?'nav-item active':'nav-item'}><Activity size={17}/> Runs</NavLink><NavLink to="/app/candidates" className={({isActive})=>isActive?'nav-item active':'nav-item'}><Search size={17}/> Candidate pool</NavLink><NavLink to="/app/categories" className={({isActive})=>isActive?'nav-item active':'nav-item'}><Settings2 size={17}/> Categories</NavLink></nav><div className="side-bottom"><div className="side-note"><div className="side-note-icon"><CircleHelp size={16}/></div><div><strong>Evidence first</strong><p>Comparisons cite retrieved public sources.</p></div></div><div className="profile-row"><span className="avatar">R</span><span className="profile-copy"><strong>Research workspace</strong><small>Local instance</small></span></div></div></aside>
    {menuOpen&&<button className="scrim" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>}
    <div className="main-shell"><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Menu size={20}/></button><div className="crumb">Workspace <ChevronRight size={14}/><span>{pageName(location.pathname)}</span></div><div className="top-actions"><HealthPill/><button className="icon-btn" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} title="Toggle theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><span className="avatar avatar-small" aria-label="Research workspace">R</span></div></header><main className="content"><Routes><Route path="/" element={<Dashboard notify={notify}/>}/><Route path="/app/reports" element={<Reports/>}/><Route path="/app/reports/:id" element={<ReportDetail/>}/><Route path="/app/runs" element={<Runs/>}/><Route path="/app/runs/:id" element={<RunDetail/>}/><Route path="/app/categories" element={<Categories notify={notify}/>}/><Route path="/app/candidates" element={<Candidates/>}/><Route path="/app/style-guide" element={<StyleGuide/>}/><Route path="*" element={<NotFound/>}/></Routes></main><footer className="app-footer"><span>Compare · Product research</span><span>Public information · UTC timestamps</span></footer></div>
    {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  </div>
}

function pageName(path){if(path.startsWith('/app/reports/'))return 'Report detail';if(path.startsWith('/app/runs/'))return 'Run detail';return ({'/':'Overview','/app/reports':'Reports','/app/runs':'Runs','/app/categories':'Categories','/app/candidates':'Candidate pool','/app/style-guide':'Style guide'})[path]||'Overview'}
function HealthPill(){const [online,setOnline]=useState(null);useEffect(()=>{let live=true;const check=async()=>{try{const r=await fetch('/health');if(live)setOnline(r.ok)}catch{if(live)setOnline(false)}};check();const timer=setInterval(check,30000);return()=>{live=false;clearInterval(timer)}},[]);return <span className={`server-state ${online===false?'offline':''}`}><i/>{online===null?'Checking API':online?'API connected':'API offline'}</span>}
function PageHeader({eyebrow,title,description,action}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>{action&&<div className="heading-action">{action}</div>}</div>}
function SectionHeading({title,action}){return <div className="section-heading"><h2>{title}</h2>{action}</div>}
function Badge({status}){const label=status==='ok'?'Completed':titleStage(status||'pending');return <span className={`badge badge-${String(status||'pending').toLowerCase()}`}>{label}</span>}
function Empty({title,body,action}){return <div className="empty-state"><span className="empty-icon"><FileText size={20}/></span><h3>{title}</h3><p>{body}</p>{action}</div>}
function Loading({rows=3}){return <div className="loading-list" aria-label="Loading">{Array.from({length:rows},(_,i)=><div key={i} className="loading-row"><i/><i/><i/></div>)}</div>}
function ErrorState({error,onRetry}){return <div className="error-state"><div><strong>We couldn’t load this view</strong><p>{error}</p></div>{onRetry&&<button className="btn btn-secondary btn-small" onClick={onRetry}>Try again</button>}</div>}

function Dashboard({notify}){
  const runs=useData(getRuns);const categories=useData(getCategories);const reports=useData(getReports);const [category,setCategory]=useState('');const [starting,setStarting]=useState(false);const nav=useNavigate();
  useEffect(()=>{if(!category&&categories.data?.length)setCategory(categories.data.find(c=>c.active)?.name||categories.data[0].name)},[categories.data,category]);
  const active=runs.data?.find(r=>['pending','running'].includes(r.status));const lastRun=active||runs.data?.[0];const latest=reports.data?.[0];
  async function runNow(){setStarting(true);try{const run=await startRun(category||undefined);notify('Run started');nav(`/app/runs/${run.id}`)}catch(e){notify(errText(e))}finally{setStarting(false)}}
  return <><PageHeader eyebrow="RESEARCH OVERVIEW" title="Good research starts here." description="Discover software products, follow the evidence, and compare what matters." action={<button className="btn btn-primary" disabled={starting||!category} onClick={runNow}>{starting?<><span className="spinner"/> Starting</>:<><Plus size={17}/> Start a run</>}</button>}/>
  <div className="run-controls panel"><div className="field-stack"><label htmlFor="category-select">Research category</label><select id="category-select" value={category} onChange={e=>setCategory(e.target.value)} disabled={!categories.data?.length}><option value="">Choose a category</option>{categories.data?.filter(c=>c.active).map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div><div className="control-hint"><span className="live-dot"/>{active?'A research run is in progress':'Ready when you are'}{lastRun&&!active&&<span> · Last run {dateLabel(lastRun.finished_at||lastRun.started_at)}</span>}</div></div>
  <section className="section-block"><SectionHeading title="Pipeline progress" action={lastRun&&<Link className="text-link" to={`/app/runs/${lastRun.id}`}>Open run <ArrowRight size={15}/></Link>}/>{runs.loading?<Loading rows={1}/>:runs.error?<ErrorState error={runs.error} onRetry={runs.reload}/>:<Pipeline run={lastRun}/>}</section>
  <section className="section-block"><SectionHeading title="Research library" action={<Link className="text-link" to="/app/reports">All reports <ArrowRight size={15}/></Link>}/>{reports.loading?<Loading rows={2}/>:reports.error?<ErrorState error={reports.error} onRetry={reports.reload}/>:latest?<LatestReport report={latest}/>:<Empty title="No reports yet" body="Start a run to discover products and create your first comparison." action={<button className="btn btn-secondary btn-small" onClick={runNow}>Start a run <ArrowRight size={15}/></button>}/>}</section>
  <section className="section-block"><SectionHeading title="Recent runs" action={<Link className="text-link" to="/app/runs">View all <ArrowRight size={15}/></Link>}/>{runs.loading?<Loading rows={3}/>:runs.error?<ErrorState error={runs.error} onRetry={runs.reload}/>:runs.data?.length?<RunTable runs={runs.data.slice(0,5)}/>:<Empty title="No runs to show" body="Your research history will appear here."/>}</section></>
}

function Pipeline({run}){const map=new Map((run?.stages||[]).map(s=>[s.stage,s.status]));let active=stages.find(k=>map.get(k)==='running');if(!active&&run?.status==='pending')active=stages.find(k=>!map.has(k));return <div className="pipeline panel"><div className="pipeline-top"><div><span className="tiny-label">RUN {run?`#${run.id}`:'NOT STARTED'}</span><div className="pipeline-message">{run?.message||'Start a run to see the research stages move.'}</div></div>{run&&<Badge status={run.status}/>}</div><ol className="pipeline-track">{stages.map((s,i)=>{const value=map.get(s);const state=['ok','partial','done'].includes(value)?'done':value==='failed'?'failed':active===s?'running':'pending';return <li key={s} className={`pipeline-item ${state}`}><span className="pipeline-node">{state==='done'?<Check size={13}/>:state==='failed'?<X size={13}/>:String(i+1).padStart(2,'0')}</span><span>{titleStage(s)}</span></li>})}</ol></div>}

function LatestReport({report}){const m=report.matrix||{},a=m.a||{},b=m.b||{};return <Link className="latest-report panel" to={`/app/reports/${report.id}`}><div className="latest-visual"><div className="product-tile tile-a"><span>A</span><strong>{initials(a.name)}</strong><small>{a.name||'Product A'}</small></div><div className="versus">VS</div><div className="product-tile tile-b"><span>B</span><strong>{initials(b.name)}</strong><small>{b.name||'Product B'}</small></div></div><div className="latest-copy"><div className="latest-top"><span className="tiny-label">LATEST COMPARISON</span><Badge status={report.status}/></div><h3>{a.name||'Product A'} <span>vs</span> {b.name||'Product B'}</h3><p>{m.category||'Software products'} · Published {dateLabel(report.created_at)}</p><span className="inline-link">Read report <ArrowRight size={15}/></span></div><ChevronRight className="latest-chevron" size={19}/></Link>}
function initials(value=''){return value.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'—'}

function Runs(){const {data,error,loading,reload}=useData(getRuns);return <><PageHeader eyebrow="ACTIVITY" title="Runs" description="Follow each research run from discovery through publication."/><div className="toolbar"><span>{data?.length||0} runs</span><button className="btn btn-secondary btn-small" onClick={reload}>Refresh</button></div>{loading?<Loading/>:error?<ErrorState error={error} onRetry={reload}/>:data?.length?<RunTable runs={data}/>:<Empty title="No runs yet" body="Start a run from Overview to begin researching a category." action={<Link className="btn btn-primary btn-small" to="/">Go to overview</Link>}/>}</>}
function RunTable({runs}){return <div className="data-table-wrap panel"><table className="data-table"><thead><tr><th>Run</th><th>Category</th><th>Status</th><th>Started</th><th>Latest update</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td><Link className="run-id" to={`/app/runs/${r.id}`}>#{r.id}</Link></td><td>{r.category}</td><td><Badge status={r.status}/></td><td>{dateLabel(r.started_at)}</td><td className="muted-cell">{r.message}</td><td><Link className="table-arrow" to={`/app/runs/${r.id}`} aria-label={`Open run ${r.id}`}><ArrowRight size={16}/></Link></td></tr>)}</tbody></table></div>}

function RunDetail(){const {id}=useParams();const load=useCallback(()=>getRun(id),[id]);const {data,error,loading,reload}=useData(load,[load]);useEffect(()=>{if(!data||!['pending','running'].includes(data.status))return;const timer=setInterval(reload,3000);return()=>clearInterval(timer)},[data?.status,reload]);const logMap=new Map((data?.stages||[]).map(s=>[s.stage,s]));return <>{loading&&!data?<Loading rows={4}/>:error?<><Link className="back-link" to="/app/runs"><ArrowLeft size={15}/> All runs</Link><ErrorState error={error} onRetry={reload}/></>:data&&<><Link className="back-link" to="/app/runs"><ArrowLeft size={15}/> All runs</Link><PageHeader eyebrow={`${data.category} · RUN #${data.id}`} title="Run details" description={data.message} action={<Badge status={data.status}/>}/><Pipeline run={data}/>{data.error&&<div className="error-state run-error"><div><strong>Run stopped</strong><p>{data.error}</p></div></div>}<section className="section-block"><SectionHeading title="Stage timeline" action={<span className="muted-cell">Refreshes every 3 seconds while active</span>}/><div className="stage-list">{stages.map((stage,i)=>{const row=logMap.get(stage);return <article className={`stage-row ${row?.status==='failed'?'stage-failed':''}`} key={stage}><div className="stage-index">{String(i+1).padStart(2,'0')}</div><div className="stage-main"><div className="stage-title"><h3>{titleStage(stage)}</h3><Badge status={row?.status||'pending'}/></div><p>{row?.error||row?.output?.message||stageSummary(stage,row)}</p>{row?.output&&<details className="stage-details"><summary>Decision and output</summary><pre>{JSON.stringify(row.output,null,2)}</pre></details>}</div><div className="stage-duration"><Clock3 size={14}/>{row?formatDuration(row.duration_ms):'—'}</div></article>})}</div></section><section className="section-block"><SectionHeading title="Slowest steps"/><ol className="slow-steps">{[...(data.stages||[])].sort((a,b)=>b.duration_ms-a.duration_ms).slice(0,5).map(x=><li key={x.stage}><span>{titleStage(x.stage)}</span><strong>{formatDuration(x.duration_ms)}</strong></li>)}</ol>{!data.stages?.length&&<p className="muted-cell">Stage timings appear as the run progresses.</p>}</section></>}</>}
function stageSummary(key,row){if(row?.status==='failed')return row.error||'This stage stopped with an error.';return 'Waiting for the previous stage to finish.'}
function formatDuration(ms=0){if(ms<1000)return `${Math.round(ms)} ms`;return `${(ms/1000).toFixed(1)} s`}

function Reports(){const {data,error,loading,reload}=useData(getReports);const [query,setQuery]=useState('');const filtered=(data||[]).filter(r=>{const m=r.matrix||{};return `${m.category||''} ${m.a?.name||''} ${m.b?.name||''}`.toLowerCase().includes(query.toLowerCase())});return <><PageHeader eyebrow="RESEARCH LIBRARY" title="Reports" description="Side-by-side product research, saved with its source trail."/><div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reports" aria-label="Search reports"/></div><span>{filtered.length} reports</span></div>{loading?<Loading rows={4}/>:error?<ErrorState error={error} onRetry={reload}/>:filtered.length?<div className="report-grid">{filtered.map(r=><ReportCard key={r.id} report={r}/>)}</div>:<Empty title={query?'No matching reports':'No reports yet'} body={query?'Try another product or category name.':'Start a research run to publish your first comparison.'} action={!query&&<Link to="/" className="btn btn-primary btn-small">Start a run</Link>}/>}</>}
function ReportCard({report}){const m=report.matrix||{},a=m.a||{},b=m.b||{};return <Link className="report-card panel" to={`/app/reports/${report.id}`}><div className="report-card-top"><span className="tiny-label">{m.category||'SOFTWARE'}</span><Badge status={report.status}/></div><div className="report-pair"><div className="mini-product mini-a">{initials(a.name)}</div><span className="mini-vs">vs</span><div className="mini-product mini-b">{initials(b.name)}</div></div><h3>{a.name||'Product A'} <span>vs</span> {b.name||'Product B'}</h3><p>{new Date(report.created_at).toLocaleDateString([], {year:'numeric',month:'short',day:'numeric'})} <span>·</span> {m.rows?.length||0} comparison dimensions</p><span className="inline-link">Open report <ArrowRight size={15}/></span></Link>}

function ReportDetail(){const {id}=useParams();const load=useCallback(()=>getReport(id),[id]);const {data,error,loading,reload}=useData(load,[load]);const [viewer,setViewer]=useState(null);useEffect(()=>{if(!viewer)return;const close=e=>e.key==='Escape'&&setViewer(null);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[viewer]);if(loading&&!data)return <Loading rows={5}/>;if(error)return <><Link className="back-link" to="/app/reports"><ArrowLeft size={15}/> All reports</Link><ErrorState error={error} onRetry={reload}/></>;if(!data)return null;const m=data.matrix||{},a=m.a||{},b=m.b||{};const shots=data.screenshots||[];return <><Link className="back-link" to="/app/reports"><ArrowLeft size={15}/> All reports</Link><div className="report-detail-head"><div><p className="eyebrow">{m.category||'PRODUCT COMPARISON'} · {new Date(data.created_at).toLocaleDateString()}</p><h1>{a.name||'Product A'} <span className="versus-word">vs</span> {b.name||'Product B'}</h1><p className="page-description">A source-led view of what public product pages reveal and where evidence is missing.</p></div><div className="report-head-actions"><Badge status={data.status}/><a className="btn btn-secondary btn-small" href={`/reports/${id}?format=md`} download><ArrowDownToLine size={15}/> Markdown</a></div></div>
  <section className="section-block report-tldr"><div className="tldr-mark">i</div><div><span className="tiny-label">AT A GLANCE</span><p>Coverage: <strong className="color-a">Product A {Math.round((m.coverage?.a||0)*100)}%</strong><span className="tldr-sep">/</span><strong className="color-b">Product B {Math.round((m.coverage?.b||0)*100)}%</strong>. Values not found during the run remain marked as unknown.</p></div></section>
  <section className="section-block"><SectionHeading title="Comparison"/><div className="comparison-wrap panel"><table className="comparison-table"><thead><tr><th className="product-heading heading-a"><span className="product-letter letter-a">A</span><div><small>PRODUCT A</small><strong>{a.name}</strong></div></th><th className="dimension-heading">DIMENSION</th><th className="product-heading heading-b"><span className="product-letter letter-b">B</span><div><small>PRODUCT B</small><strong>{b.name}</strong></div></th></tr></thead><tbody>{(m.rows||[]).map(row=><tr key={row.dimension}><td className="value-a">{row.a}{(row.facts_a||[]).map(f=><sup key={f}>{f}</sup>)}</td><th className="dimension-cell">{titleStage(row.dimension)}</th><td className="value-b">{row.b}{(row.facts_b||[]).map(f=><sup key={f}>{f}</sup>)}</td></tr>)}</tbody></table></div><p className="table-note">A = teal · B = plum · Unknown means the detail was not publicly found.</p></section>
  <section className="section-block"><SectionHeading title="Product screenshots" action={<span className="muted-cell">{shots.length} screenshots · 2 per product</span>}/>{shots.length?<div className="capture-grid">{shots.map((shot,i)=><figure className={`capture-card ${shot.product==='B'?'capture-b':'capture-a'} ${/logo|icon/i.test(shot.caption)?'capture-logo':''}`} key={`${shot.url}-${i}`}><button onClick={()=>setViewer(shot)} aria-label={`Enlarge ${shot.caption}`}><img src={shot.url} alt={shot.caption} loading="lazy"/><span className="capture-zoom">Expand</span></button><figcaption><span className={`capture-tag ${shot.product==='B'?'tag-b':'tag-a'}`}>PRODUCT {shot.product}</span>{shot.caption}</figcaption></figure>)}</div>:<Empty title="No captures passed review" body="This run didn’t produce screenshots that met the capture quality checks."/>}</section>
  <section className="section-block"><SectionHeading title="Product notes"/><div className="notes-grid"><article className="note-panel note-a"><div className="note-head"><span className="product-letter letter-a">A</span><h3>{a.name}</h3></div><p>{a.description||'The public page did not provide a product summary that could be included here.'}</p><div className="coverage-line"><span>Evidence coverage</span><strong>{Math.round((m.coverage?.a||0)*100)}%</strong></div><div className="coverage-bar"><i style={{width:`${Math.round((m.coverage?.a||0)*100)}%`}}/></div><a href={a.url} target="_blank" rel="noreferrer">Visit product site <ExternalLink size={14}/></a></article><article className="note-panel note-b"><div className="note-head"><span className="product-letter letter-b">B</span><h3>{b.name}</h3></div><p>{b.description||'The public page did not provide a product summary that could be included here.'}</p><div className="coverage-line"><span>Evidence coverage</span><strong>{Math.round((m.coverage?.b||0)*100)}%</strong></div><div className="coverage-bar bar-b"><i style={{width:`${Math.round((m.coverage?.b||0)*100)}%`}}/></div><a href={b.url} target="_blank" rel="noreferrer">Visit product site <ExternalLink size={14}/></a></article></div></section>
  <section className="section-block"><details className="sources-panel panel"><summary><div><span className="tiny-label">TRANSPARENCY</span><strong>Sources and method</strong><small>Source pages, evidence and how to read this report</small></div><ChevronRight size={18}/></summary><div className="sources-content"><h3>Product pages</h3><ul><li><a href={a.url} target="_blank" rel="noreferrer">{a.name}: {a.url}<ExternalLink size={13}/></a></li><li><a href={b.url} target="_blank" rel="noreferrer">{b.name}: {b.url}<ExternalLink size={13}/></a></li></ul><h3>Method</h3><p>Facts are extracted from the public pages fetched for this run. Citations refer to saved fact records. “Not publicly found” means the crawler did not locate a source for that field; it does not mean the product lacks that capability.</p>{(m.facts||[]).length>0&&<><h3>Verified facts</h3><div className="fact-list">{m.facts.map(f=><article className="fact-item" key={f.id}><span className="fact-id">{f.id}</span><div><strong>{f.field} · {f.product==='A'?a.name:b.name}</strong><blockquote>“{f.quote}”</blockquote><a href={f.source_url} target="_blank" rel="noreferrer">Open source <ExternalLink size={13}/></a></div></article>)}</div></>}</div></details></section>{viewer&&<div className="viewer-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setViewer(null)}><div className="viewer"><button className="icon-btn viewer-close" onClick={()=>setViewer(null)} aria-label="Close image"><X/></button><img src={viewer.url} alt={viewer.caption}/><p>{viewer.caption}</p></div></div>}</>}
