import { useCallback, useEffect, useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom';
import { Activity, ArrowDownToLine, ArrowLeft, ArrowRight, BarChart3, Check, ChevronRight, CircleHelp, Clock3, ExternalLink, FileText, Filter, LayoutDashboard, LayoutGrid, Menu, Moon, Plus, Search, Settings2, Sun, X } from 'lucide-react';
import { getCategories, getReport, getReports, getRun, getRuns, startRun } from './api.js';
import { Categories, Candidates, ComparisonHub, NotFound, StyleGuide } from './ExtraPages.jsx';

const stages = ['collect','score','select','research_a','research_b','screenshots','compare','write','render'];
const titleStage = (value='') => value.replaceAll('_',' ').replace(/\b\w/g, m => m.toUpperCase());
const dateLabel = value => value ? new Date(value).toLocaleString([], { month:'short', day:'numeric', hour:'numeric', minute:'2-digit' }) : 'Not started';
const errText = e => e?.message || 'The request could not be completed.';

function useData(load, deps=[]) {
  const [state,setState]=useState({loading:true,error:'',data:null});
  const reload=useCallback(async()=>{setState(s=>({...s,loading:true,error:''}));try{setState({loading:false,error:'',data:await load()})}catch(e){setState({loading:false,error:errText(e),data:null})}},deps);
  useEffect(()=>{reload()},[reload]); return {...state,reload};
}

export default function App(){
  const [toast,setToast]=useState(''); const [menuOpen,setMenuOpen]=useState(false); const [theme,setTheme]=useState(()=>localStorage.getItem('compare-theme')||'light'); const location=useLocation();
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('compare-theme',theme)},[theme]);
  useEffect(()=>{setMenuOpen(false)},[location.pathname]);
  const notify=message=>{setToast(message);window.clearTimeout(window.__compareToast);window.__compareToast=window.setTimeout(()=>setToast(''),3400)};
  return <div className="app-shell"><aside className={`sidebar ${menuOpen?'sidebar-open':''}`}><div className="side-brand"><div className="brand-mark"><BarChart3 size={19}/></div><span>Compare<span className="brand-dot">.</span><small>RESEARCH WORKSPACE</small></span><button className="icon-btn mobile-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu"><X size={18}/></button></div><div className="workspace-label">WORKSPACE</div><nav className="side-nav" aria-label="Main navigation">
    <NavLink end to="/" className={({isActive})=>isActive?'nav-item active':'nav-item'}><LayoutDashboard size={17}/> Overview</NavLink><NavLink to="/app/compare" className={({isActive})=>isActive?'nav-item active':'nav-item'}><LayoutGrid size={17}/> Compare tools</NavLink><NavLink to="/app/reports" className={({isActive})=>isActive?'nav-item active':'nav-item'}><FileText size={17}/> Reports</NavLink><NavLink to="/app/runs" className={({isActive})=>isActive?'nav-item active':'nav-item'}><Activity size={17}/> Runs</NavLink><NavLink to="/app/candidates" className={({isActive})=>isActive?'nav-item active':'nav-item'}><Search size={17}/> Candidate pool</NavLink><NavLink to="/app/categories" className={({isActive})=>isActive?'nav-item active':'nav-item'}><Settings2 size={17}/> Categories</NavLink></nav><div className="side-bottom"><div className="side-note"><div className="side-note-icon"><CircleHelp size={16}/></div><div><strong>Evidence first</strong><p>Comparisons cite retrieved public sources.</p></div></div><div className="profile-row"><span className="avatar">R</span><span className="profile-copy"><strong>Research workspace</strong><small>Local instance</small></span></div></div></aside>
    {menuOpen&&<button className="scrim" aria-label="Close navigation" onClick={()=>setMenuOpen(false)}/>}
    <div className="main-shell"><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMenuOpen(true)} aria-label="Open menu"><Menu size={20}/></button><div className="crumb">Workspace <ChevronRight size={14}/><span>{pageName(location.pathname)}</span></div><div className="top-actions"><HealthPill/><button className="icon-btn" aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} title="Toggle theme" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><span className="avatar avatar-small" aria-label="Research workspace">R</span></div></header><main className="content"><Routes><Route path="/" element={<Dashboard notify={notify}/>}/><Route path="/app/compare" element={<ComparisonHub/>}/><Route path="/app/reports" element={<Reports/>}/><Route path="/app/reports/:id" element={<ReportDetail/>}/><Route path="/app/runs" element={<Runs/>}/><Route path="/app/runs/:id" element={<RunDetail/>}/><Route path="/app/categories" element={<Categories notify={notify}/>}/><Route path="/app/candidates" element={<Candidates/>}/><Route path="/app/style-guide" element={<StyleGuide/>}/><Route path="*" element={<NotFound/>}/></Routes></main><footer className="app-footer"><span>Compare · Product research</span><span>Public information · UTC timestamps</span></footer></div>
    {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}
  </div>
}

function pageName(path){if(path.startsWith('/app/reports/'))return 'Report detail';if(path.startsWith('/app/runs/'))return 'Run detail';return ({'/':'Overview','/app/reports':'Reports','/app/compare':'Compare tools','/app/runs':'Runs','/app/categories':'Categories','/app/candidates':'Candidate pool','/app/style-guide':'Style guide'})[path]||'Overview'}
function HealthPill(){const [online,setOnline]=useState(null);useEffect(()=>{let live=true;const check=async()=>{try{const r=await fetch('/health');if(live)setOnline(r.ok)}catch{if(live)setOnline(false)}};check();const timer=setInterval(check,30000);return()=>{live=false;clearInterval(timer)}},[]);return <span className={`server-state ${online===false?'offline':''}`}><i/>{online===null?'Checking API':online?'API connected':'API offline'}</span>}
function PageHeader({eyebrow,title,description,action}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description&&<p className="page-description">{description}</p>}</div>{action&&<div className="heading-action">{action}</div>}</div>}
function SectionHeading({title,action}){return <div className="section-heading"><h2>{title}</h2>{action}</div>}
function Badge({status}){const label=status==='ok'?'Completed':titleStage(status||'pending');return <span className={`badge badge-${String(status||'pending').toLowerCase()}`}>{label}</span>}
function Empty({title,body,action}){return <div className="empty-state"><span className="empty-icon"><FileText size={20}/></span><h3>{title}</h3><p>{body}</p>{action}</div>}
function Loading({rows=3}){return <div className="loading-list" aria-label="Loading">{Array.from({length:rows},(_,i)=><div key={i} className="loading-row"><i/><i/><i/></div>)}</div>}
function ErrorState({error,onRetry}){return <div className="error-state"><div><strong>We couldn’t load this view</strong><p>{error}</p></div>{onRetry&&<button className="btn btn-secondary btn-small" onClick={onRetry}>Try again</button>}</div>}

function Dashboard({notify}){
  const runs=useData(getRuns);const categories=useData(getCategories);const reports=useData(getReports);const [category,setCategory]=useState('');const [starting,setStarting]=useState(false);const nav=useNavigate();
  useEffect(()=>{if(!category&&categories.data?.length)setCategory(categories.data.find(c=>c.active)?.name||categories.data[0].name)},[categories.data,category]);
  const active=runs.data?.find(r=>['pending','running'].includes(r.status));const lastRun=active||runs.data?.[0];const latest=reports.data?.[0];
  async function runNow(){setStarting(true);try{const run=await startRun(category||undefined);notify('Run started');nav(`/app/runs/${run.id}`)}catch(e){notify(errText(e))}finally{setStarting(false)}}
  return <><PageHeader eyebrow="RESEARCH OVERVIEW" title="Good research starts here." description="Discover software products, follow the evidence, and compare what matters." action={<button className="btn btn-primary" disabled={starting||!category} onClick={runNow}>{starting?<><span className="spinner"/> Starting</>:<><Plus size={17}/> Start a run</>}</button>}/>
  <div className="run-controls panel"><div className="field-stack"><label htmlFor="category-select">Research category</label><select id="category-select" value={category} onChange={e=>setCategory(e.target.value)} disabled={!categories.data?.length}><option value="">Choose a category</option>{categories.data?.filter(c=>c.active).map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div><div className="control-hint"><span className="live-dot"/>{active?'A research run is in progress':'Ready when you are'}{lastRun&&!active&&<span> · Last run {dateLabel(lastRun.finished_at||lastRun.started_at)}</span>}</div></div>
  <section className="section-block"><SectionHeading title="Pipeline progress" action={lastRun&&<Link className="text-link" to={`/app/runs/${lastRun.id}`}>Open run <ArrowRight size={15}/></Link>}/>{runs.loading?<Loading rows={1}/>:runs.error?<ErrorState error={runs.error} onRetry={runs.reload}/>:<Pipeline run={lastRun}/>}</section>
  <section className="section-block"><SectionHeading title="Research library" action={<Link className="text-link" to="/app/reports">All reports <ArrowRight size={15}/></Link>}/>{reports.loading?<Loading rows={2}/>:reports.error?<ErrorState error={reports.error} onRetry={reports.reload}/>:latest?<LatestReport report={latest}/>:<Empty title="No reports yet" body="Start a run to discover products and create your first comparison." action={<button className="btn btn-secondary btn-small" onClick={runNow}>Start a run <ArrowRight size={15}/></button>}/>}</section>
  <section className="section-block"><SectionHeading title="Recent runs" action={<Link className="text-link" to="/app/runs">View all <ArrowRight size={15}/></Link>}/>{runs.loading?<Loading rows={3}/>:runs.error?<ErrorState error={runs.error} onRetry={runs.reload}/>:runs.data?.length?<RunTable runs={runs.data.slice(0,5)}/>:<Empty title="No runs to show" body="Your research history will appear here."/>}</section></>
}

function Pipeline({run}){const map=new Map((run?.stages||[]).map(s=>[s.stage,s.status]));let active=stages.find(k=>map.get(k)==='running');if(!active&&run?.status==='pending')active=stages.find(k=>!map.has(k));return <div className="pipeline panel"><div className="pipeline-top"><div><span className="tiny-label">RUN {run?`#${run.id}`:'NOT STARTED'}</span><div className="pipeline-message">{run?.message||'Start a run to see the research stages move.'}</div></div>{run&&<Badge status={run.status}/>}</div><ol className="pipeline-track">{stages.map((s,i)=>{const value=map.get(s);const state=['ok','partial','done'].includes(value)?'done':value==='failed'?'failed':active===s?'running':'pending';return <li key={s} className={`pipeline-item ${state}`}><span className="pipeline-node">{state==='done'?<Check size={13}/>:state==='failed'?<X size={13}/>:String(i+1).padStart(2,'0')}</span><span>{titleStage(s)}</span></li>})}</ol></div>}

function LatestReport({report}){const m=report.matrix||{},a=m.a||{},b=m.b||{};return <Link className="latest-report panel" to={`/app/reports/${report.id}`}><div className="latest-visual"><div className="product-tile tile-a"><span>A</span><strong>{initials(a.name)}</strong><small>{a.name||'Product A'}</small></div><div className="versus">VS</div><div className="product-tile tile-b"><span>B</span><strong>{initials(b.name)}</strong><small>{b.name||'Product B'}</small></div></div><div className="latest-copy"><div className="latest-top"><span className="tiny-label">LATEST COMPARISON</span><Badge status={report.status}/></div><h3>{a.name||'Product A'} <span>vs</span> {b.name||'Product B'}</h3><p>{m.category||'Software products'} · Published {dateLabel(report.created_at)}</p><span className="inline-link">Read report <ArrowRight size={15}/></span></div><ChevronRight className="latest-chevron" size={19}/></Link>}
function initials(value=''){return value.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'—'}

function Runs(){const {data,error,loading,reload}=useData(getRuns);return <><PageHeader eyebrow="ACTIVITY" title="Runs" description="Follow each research run from discovery through publication."/><div className="toolbar"><span>{data?.length||0} runs</span><button className="btn btn-secondary btn-small" onClick={reload}>Refresh</button></div>{loading?<Loading/>:error?<ErrorState error={error} onRetry={reload}/>:data?.length?<RunTable runs={data}/>:<Empty title="No runs yet" body="Start a run from Overview to begin researching a category." action={<Link className="btn btn-primary btn-small" to="/">Go to overview</Link>}/>}</>}
function RunTable({runs}){return <div className="data-table-wrap panel"><table className="data-table"><thead><tr><th>Run</th><th>Category</th><th>Status</th><th>Started</th><th>Latest update</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td><Link className="run-id" to={`/app/runs/${r.id}`}>#{r.id}</Link></td><td>{r.category}</td><td><Badge status={r.status}/></td><td>{dateLabel(r.started_at)}</td><td className="muted-cell">{r.message}</td><td><Link className="table-arrow" to={`/app/runs/${r.id}`} aria-label={`Open run ${r.id}`}><ArrowRight size={16}/></Link></td></tr>)}</tbody></table></div>}

function RunDetail(){
  const {id}=useParams();
  const load=useCallback(()=>getRun(id),[id]);
  const {data,error,loading,reload}=useData(load,[load]);
  useEffect(()=>{
    if(!data||!['pending','running'].includes(data.status))return;
    const timer=setInterval(reload,3000);
    return()=>clearInterval(timer)
  },[data?.status,reload]);
  const logMap=new Map((data?.stages||[]).map(s=>[s.stage,s]));
  const usage=data?.token_usage||{input_tokens:0,output_tokens:0,total_tokens:0,calls:0};
  const failure=data?.failure||(data?.status==='failed'&&data?.error?{reason:data.error}:null);
  return <>
    {loading&&!data?<Loading rows={4}/>:error?<><Link className="back-link" to="/app/runs"><ArrowLeft size={15}/> All runs</Link><ErrorState error={error} onRetry={reload}/></>:data&&<>
      <Link className="back-link" to="/app/runs"><ArrowLeft size={15}/> All runs</Link>
      <PageHeader eyebrow={`${data.category} · RUN #${data.id}`} title="Run details" description={data.message} action={<Badge status={data.status}/>}/>
      <Pipeline run={data}/>
      {failure&&<div className="error-state run-error"><div><strong>{failure.stage?`Failed during ${titleStage(failure.stage)}`:'Run failed'}</strong><p>{failure.reason}</p></div></div>}
      <section className="section-block">
        <SectionHeading title="Token usage" action={<span className="muted-cell">{usage.calls} AI calls</span>}/>
        <div className="token-grid">
          <article className="token-card panel"><span>INPUT TOKENS</span><strong>{Number(usage.input_tokens||0).toLocaleString()}</strong></article>
          <article className="token-card panel"><span>OUTPUT TOKENS</span><strong>{Number(usage.output_tokens||0).toLocaleString()}</strong></article>
          <article className="token-card panel"><span>TOTAL TOKENS</span><strong>{Number(usage.total_tokens||0).toLocaleString()}</strong></article>
        </div>
        <p className="token-note">{usage.calls?`Usage totals are reported by the provider across ${usage.calls} AI calls.`:'No AI model calls were made in this run; the pipeline used deterministic processing, so token usage is 0.'}</p>
      </section>
      <section className="section-block">
        <SectionHeading title="Stage timeline" action={<span className="muted-cell">Refreshes every 3 seconds while active</span>}/>
        <div className="stage-list">{stages.map((stage,i)=>{const row=logMap.get(stage);return <article className={`stage-row ${row?.status==='failed'?'stage-failed':''}`} key={stage}>
          <div className="stage-index">{String(i+1).padStart(2,'0')}</div>
          <div className="stage-main"><div className="stage-title"><h3>{titleStage(stage)}</h3><Badge status={row?.status||'pending'}/></div>
            <p>{row?.error||row?.output?.message||stageSummary(stage,row)}</p>
            {row?.output&&<details className="stage-details"><summary>Decision and output</summary><pre>{JSON.stringify(row.output,null,2)}</pre></details>}
          </div>
          <div className="stage-duration"><Clock3 size={14}/>{row?formatDuration(row.duration_ms):'—'}</div>
        </article>})}</div>
      </section>
      <section className="section-block"><SectionHeading title="Slowest steps"/><ol className="slow-steps">{[...(data.stages||[])].sort((a,b)=>b.duration_ms-a.duration_ms).slice(0,5).map(x=><li key={x.stage}><span>{titleStage(x.stage)}</span><strong>{formatDuration(x.duration_ms)}</strong></li>)}</ol>{!data.stages?.length&&<p className="muted-cell">Stage timings appear as the run progresses.</p>}</section>
    </>}
  </>
}
function stageSummary(key,row){if(row?.status==='failed')return row.error||'This stage stopped with an error.';if(row?.status==='partial')return row.output?.message||'Stage finished with partial results.';if(row?.status==='ok'||row?.status==='done')return row.output?.message||'Stage completed successfully.';if(row?.status==='running')return row.output?.message||'Stage is running.';return 'Waiting for the previous stage to finish.'}
function formatDuration(ms=0){if(ms<1000)return `${Math.round(ms)} ms`;return `${(ms/1000).toFixed(1)} s`}

function Reports(){const {data,error,loading,reload}=useData(getReports);const [query,setQuery]=useState('');const filtered=(data||[]).filter(r=>{const m=r.matrix||{};return `${m.category||''} ${m.a?.name||''} ${m.b?.name||''}`.toLowerCase().includes(query.toLowerCase())});return <><PageHeader eyebrow="RESEARCH LIBRARY" title="Reports" description="Side-by-side product research, saved with its source trail."/><div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reports" aria-label="Search reports"/></div><span>{filtered.length} reports</span></div>{loading?<Loading rows={4}/>:error?<ErrorState error={error} onRetry={reload}/>:filtered.length?<div className="report-grid">{filtered.map(r=><ReportCard key={r.id} report={r}/>)}</div>:<Empty title={query?'No matching reports':'No reports yet'} body={query?'Try another product or category name.':'Start a research run to publish your first comparison.'} action={!query&&<Link to="/" className="btn btn-primary btn-small">Start a run</Link>}/>}</>}
function ReportCard({report}){const m=report.matrix||{},a=m.a||{},b=m.b||{};return <Link className="report-card panel" to={`/app/reports/${report.id}`}><div className="report-card-top"><span className="tiny-label">{m.category||'SOFTWARE'}</span><Badge status={report.status}/></div><div className="report-pair"><div className="mini-product mini-a">{initials(a.name)}</div><span className="mini-vs">vs</span><div className="mini-product mini-b">{initials(b.name)}</div></div><h3>{a.name||'Product A'} <span>vs</span> {b.name||'Product B'}</h3><p>{new Date(report.created_at).toLocaleDateString([], {year:'numeric',month:'short',day:'numeric'})} <span>·</span> {m.rows?.length||0} comparison dimensions</p><span className="inline-link">Open report <ArrowRight size={15}/></span></Link>}

function ReportDetail(){
  const {id}=useParams();
  const load=useCallback(()=>getReport(id),[id]);
  const {data,error,loading,reload}=useData(load,[load]);
  const [viewer,setViewer]=useState(null);
  useEffect(()=>{if(!viewer)return;const close=e=>e.key==='Escape'&&setViewer(null);window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[viewer]);
  if(loading&&!data)return <Loading rows={5}/>;
  if(error)return <><Link className="back-link" to="/app/compare"><ArrowLeft size={15}/> Compare tools</Link><ErrorState error={error} onRetry={reload}/></>;
  if(!data)return null;
  const m=data.matrix||{},a=m.a||{},b=m.b||{},shots=data.screenshots||[],facts=m.facts||[],sources=m.sources?.length?m.sources:[{product:'A',url:a.url,topic:'home'},{product:'B',url:b.url,topic:'home'}];
  const factsA=facts.filter(f=>f.product==='A'),factsB=facts.filter(f=>f.product==='B');
  const pricing=(m.rows||[]).find(r=>r.dimension==='pricing');
  const features=(m.rows||[]).find(r=>r.dimension==='features');
  const read=(v)=>!v||/not publicly found/i.test(v)?'Not found in the pages reviewed':v;
  const decisionRows=[
    ['Pricing evidence',pricing?`${a.name}: ${read(pricing.a)} · ${b.name}: ${read(pricing.b)}`:'Pricing was not available in the report data.'],
    ['Feature evidence',features?`${a.name}: ${read(features.a)} · ${b.name}: ${read(features.b)}`:'Feature evidence was not available in the report data.'],
    ['Overall recommendation','No winner is assigned because the available public evidence is not enough to verify a complete side-by-side fit.']
  ];
  const fitRows=[
    ['Understand each product',a.name,a.description||'A product summary was not found in the retrieved page.'],
    ['Understand each product',b.name,b.description||'A product summary was not found in the retrieved page.'],
    ['Compare price and plan limits','Both products','The available research does not establish equivalent plan tiers, usage limits, or a total cost for the same team size.']
  ];
  return <>
    <Link className="back-link" to={`/app/compare?category=${encodeURIComponent(m.category||'')}`}><ArrowLeft size={15}/> {m.category||'Compare tools'}</Link>
    <div className="report-detail-head"><div><p className="eyebrow">{m.category||'PRODUCT COMPARISON'} · {new Date(data.created_at).toLocaleDateString()}</p><h1>{a.name||'Product A'} <span className="versus-word">vs</span> {b.name||'Product B'}</h1><p className="page-description">Evidence-led comparison · unknowns are called out where public pages did not provide an answer.</p></div><div className="report-head-actions"><Badge status={data.status}/><a className="btn btn-secondary btn-small" href={`/reports/${id}?format=md`} download><ArrowDownToLine size={15}/> Markdown</a></div></div>
    <section className="section-block report-tldr"><div className="tldr-mark">i</div><div><span className="tiny-label">RESEARCH COVERAGE</span><p>Product A <strong>{Math.round((m.coverage?.a||0)*100)}%</strong><span className="tldr-sep">·</span>Product B <strong>{Math.round((m.coverage?.b||0)*100)}%</strong>. Coverage reflects the public evidence retrieved for this report.</p></div></section>

    <section className="section-block"><SectionHeading title="Quick decision verdict"/><div className="table-wrap panel"><table className="long-table"><thead><tr><th>Decision category</th><th>Evidence-based finding</th></tr></thead><tbody>{decisionRows.map(([label,value])=><tr key={label}><th>{label}</th><td>{value}</td></tr>)}</tbody></table></div></section>

    <section className="section-block"><SectionHeading title={`${a.name} vs ${b.name} at a glance`} action={<span className="muted-cell">Product homepages</span>}/><div className="product-snapshot-grid">{[[a,'A'],[b,'B']].map(([product,label])=><article className={`snapshot-card panel snapshot-${label.toLowerCase()}`} key={label}><div className="snapshot-top"><span className={`product-letter letter-${label.toLowerCase()}`}>{label}</span><div><h3>{product.name}</h3><a href={product.url} target="_blank" rel="noreferrer">Official site <ExternalLink size={13}/></a></div></div><p>{product.description||'No product summary was found in the pages reviewed.'}</p><dl><div><dt>Starting price</dt><dd>{read(label==='A'?pricing?.a:pricing?.b)}</dd></div><div><dt>Feature evidence</dt><dd>{read(label==='A'?features?.a:features?.b)}</dd></div><div><dt>Evidence coverage</dt><dd>{Math.round((m.coverage?.[label.toLowerCase()]||0)*100)}%</dd></div></dl></article>)}</div></section>

    <section className="section-block"><SectionHeading title="Product screenshots" action={<span className="muted-cell">Homepage + logo/icon per product · {shots.length} captures</span>}/>{shots.length?<div className="capture-grid">{shots.map((shot,i)=><figure className={`capture-card ${shot.product==='B'?'capture-b':'capture-a'} ${/logo|icon/i.test(shot.caption)?'capture-logo':''}`} key={`${shot.url}-${i}`}><button onClick={()=>setViewer(shot)} aria-label={`Enlarge ${shot.caption}`}><img src={shot.url} alt={shot.caption} loading="lazy"/><span className="capture-zoom">Expand</span></button><figcaption><span className={`capture-tag ${shot.product==='B'?'tag-b':'tag-a'}`}>PRODUCT {shot.product}</span>{shot.caption}</figcaption></figure>)}</div>:<Empty title="No captures passed review" body="This run didn’t produce product screenshots."/>}</section>

    <section className="section-block"><SectionHeading title="Feature-by-feature matrix"/><p className="section-intro">Capabilities and pricing are compared only where this run retrieved evidence.</p><div className="table-wrap panel"><table className="long-table matrix-table"><thead><tr><th>Capability</th><th>Why it matters</th><th>{a.name}</th><th>{b.name}</th><th>Finding</th></tr></thead><tbody>{(m.rows||[]).map(row=><tr key={row.dimension}><th>{titleStage(row.dimension)}</th><td>{row.dimension==='pricing'?'Helps estimate fit against budget and plan limits.':'Shows what the public product pages say the product can do.'}</td><td>{read(row.a)}{row.facts_a?.length>0&&<sup>{row.facts_a.join(', ')}</sup>}</td><td>{read(row.b)}{row.facts_b?.length>0&&<sup>{row.facts_b.join(', ')}</sup>}</td><td>{row.verdict==='unknown'?'Not enough matched evidence':'See cited evidence'}</td></tr>)}</tbody></table></div>{!(m.rows||[]).length&&<Empty title="No comparable fields found" body="The run did not retrieve enough structured information to build a feature matrix."/>}</section>

    <section className="section-block"><SectionHeading title="Technical deep dives"/><p className="section-intro">Summaries below use each product’s retrieved description and verified fact excerpts.</p><div className="deep-dive-grid">{[[a,'A',factsA],[b,'B',factsB]].map(([product,label,items])=><article className="deep-dive-card panel" key={label}><div className="deep-dive-title"><span className={`product-letter letter-${label.toLowerCase()}`}>{label}</span><div><span className="tiny-label">PRODUCT {label}</span><h3>{product.name}</h3></div></div><p>{product.description||'A detailed public product description was not found.'}</p><h4>Verified details</h4>{items.length?<ul>{items.map((fact,i)=><li key={`${fact.id||fact.field}-${i}`}><strong>{titleStage(fact.field)}:</strong> {fact.quote||fact.value} <sup>{fact.id}</sup></li>)}</ul>:<p className="unknown-copy">No additional technical facts were verified in the pages reviewed.</p>}</article>)}</div></section>

    <section className="section-block"><SectionHeading title="Pricing & total cost of ownership"/><div className="pricing-analysis panel"><div className="pricing-columns">{[[a,'A'],[b,'B']].map(([product,label])=><div key={label}><span className="tiny-label">{product.name}</span><strong>{read(label==='A'?pricing?.a:pricing?.b)}</strong><p>{(label==='A'?factsA:factsB).some(f=>f.field==='pricing')?'A pricing-related statement was found; plan equivalence and included limits still need confirmation.':'No pricing statement was found in the pages reviewed.'}</p></div>)}</div><div className="cost-note"><strong>Comparable total cost is unavailable.</strong><p>The retrieved evidence does not establish equivalent plans, user counts, usage levels, or add-on costs. A cost estimate would be misleading without those details.</p></div></div></section>

    <section className="section-block"><SectionHeading title="Which product fits your use case?"/><div className="table-wrap panel"><table className="long-table"><thead><tr><th>Use case</th><th>Product evidence</th><th>Recommendation</th></tr></thead><tbody>{fitRows.map(([useCase,product,detail],i)=><tr key={`${useCase}-${i}`}><th>{useCase}</th><td><strong>{product}:</strong> {detail}</td><td>{i<2?'Review the linked source and confirm requirements with the vendor.':'Not enough evidence to rank the products.'}</td></tr>)}</tbody></table></div></section>

    <section className="section-block"><SectionHeading title="Where each product falls short"/><p className="section-intro">Limitations are included only when supported by the retrieved sources.</p><div className="deep-dive-grid">{[[a,'A',factsA],[b,'B',factsB]].map(([product,label,items])=><article className="limitation-card panel" key={label}><span className="tiny-label">{product.name.toUpperCase()}</span>{items.some(f=>f.field==='limitations'||f.field==='cons')?<ul>{items.filter(f=>f.field==='limitations'||f.field==='cons').map((f,i)=><li key={i}>{f.quote||f.value}</li>)}</ul>:<p>No independently verified product limitation was extracted in this run. This does not mean the product has no limitations.</p>}</article>)}</div></section>

    <section className="section-block"><SectionHeading title="The switching playbook"/><p className="section-intro">Use verified differences to plan evaluation; the run did not retrieve migration documentation.</p><div className="switching-grid">{[[a,'A'],[b,'B']].map(([product,label])=><article className="switching-card panel" key={label}><span className="tiny-label">MOVING TO {product.name.toUpperCase()}</span><h3>What the report confirms</h3><ul><li>{product.description||'Product positioning was not described in the retrieved pages.'}</li>{(label==='A'?factsA:factsB).slice(0,3).map((f,i)=><li key={i}>{f.quote||f.value}</li>)}</ul><h3>What to verify before switching</h3><p>Confirm data export, migration support, plan limits, integrations, and contract terms directly with the vendor. These details were not established by this run.</p></article>)}</div></section>

    <section className="section-block"><SectionHeading title="Frequently asked questions"/><div className="faq-list">{[
      ['Which product is cheaper?',pricing&&pricing.a!=='not publicly found'&&pricing.b!=='not publicly found'?`The retrieved pages list ${a.name} at ${pricing.a} and ${b.name} at ${pricing.b}. Billing periods and included limits must be checked before treating these as equivalent.`:'The run did not find comparable pricing for both products.'],
      ['Which product has more features?',features&&features.a!=='not publicly found'&&features.b!=='not publicly found'?`The retrieved pages mention ${a.name}: ${features.a}; ${b.name}: ${features.b}. These excerpts do not provide a complete feature inventory.`:'The run did not find matched feature lists for both products.'],
      ['Which one should I choose?','There is not enough verified evidence in this report to name an overall winner. Compare the sources against your own requirements and confirm any missing details with the vendors.'],
      ['How current is this comparison?',`This report was generated on ${new Date(data.created_at).toLocaleDateString()}. Prices and product capabilities can change; check the linked official sources before making a purchase.`]
    ].map(([question,answer])=><details className="faq-item panel" key={question}><summary>{question}<ChevronRight size={17}/></summary><p>{answer}</p></details>)}</div></section>

    <section className="section-block"><SectionHeading title="Final verdict & recommendation"/><div className="final-verdict panel"><span className="eyebrow">EVIDENCE-LED RESULT</span><h3>No overall winner assigned</h3><p>The report has limited public evidence for a reliable recommendation. Review the verified pricing and feature excerpts above, then confirm missing plan and workflow details with both vendors.</p><div className="verdict-coverage"><span>{a.name} · {Math.round((m.coverage?.a||0)*100)}% evidence coverage</span><span>{b.name} · {Math.round((m.coverage?.b||0)*100)}% evidence coverage</span></div></div></section>

    <section className="section-block"><details className="sources-panel panel" open><summary><div><span className="tiny-label">TRANSPARENCY</span><strong>Sources & methodology</strong><small>Source pages, evidence, and how to read this comparison</small></div><ChevronRight size={18}/></summary><div className="sources-content"><h3>Official product pages</h3><ul>{sources.map((source,i)=><li key={`${source.product}-${source.url}-${i}`}>Product {source.product} · {titleStage(source.topic)}: <a href={source.url} target="_blank" rel="noreferrer">{source.url}<ExternalLink size={13}/></a></li>)}</ul><h3>Verified source excerpts</h3>{facts.length?<div className="fact-list">{facts.map((f,i)=><article className="fact-item" key={`${f.id||i}-${i}`}><span className="fact-id">{f.id||`F${i+1}`}</span><div><strong>{f.field} · {f.product==='A'?a.name:b.name}</strong><blockquote>“{f.quote||f.value}”</blockquote><a href={f.source_url} target="_blank" rel="noreferrer">Open source <ExternalLink size={13}/></a></div></article>)}</div>:<p>No quotable fact records were saved for this run.</p>}<h3>Method</h3><p>This report uses public pages retrieved during the run. The feature matrix and pricing notes include only captured evidence. “Not found” means the crawler did not locate the detail in its reviewed pages; it does not mean a product lacks that feature. Verify current pricing, product limits, and technical claims with the official sources before purchase.</p></div></details></section>
    {viewer&&<div className="viewer-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&setViewer(null)}><div className="viewer"><button className="icon-btn viewer-close" onClick={()=>setViewer(null)} aria-label="Close image"><X/></button><img src={viewer.url} alt={viewer.caption}/><p>{viewer.caption}</p></div></div>}
  </>;
}
