import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ExternalLink, FileText, Plus, Search, Settings2 } from 'lucide-react';
import { createCategory, getCandidates, getCategories, updateCategory } from './api.js';

export function Categories({ notify }) {
  const [rows,setRows]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[name,setName]=useState(''),[keywords,setKeywords]=useState('');
  async function reload(){setLoading(true);setError('');try{setRows(await getCategories())}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{reload()},[]);
  async function submit(e){e.preventDefault();setSaving(true);try{await createCategory({name,keywords:keywords.split(',').map(x=>x.trim()).filter(Boolean)});setName('');setKeywords('');setShow(false);notify('Category added');reload()}catch(e){notify(e.message)}finally{setSaving(false)}}
  async function toggle(c){try{await updateCategory(c.id,{active:!c.active});notify(c.active?'Category paused':'Category activated');reload()}catch(e){notify(e.message)}}
  return <><header className="page-heading"><div><p className="eyebrow">RESEARCH SETUP</p><h1>Categories</h1><p className="page-description">Choose the topics the discovery pipeline should look for.</p></div><button className="btn btn-primary" onClick={()=>setShow(x=>!x)}><Plus size={17}/> Add category</button></header>
    {show&&<form className="category-form panel" onSubmit={submit}><div><p className="eyebrow">NEW CATEGORY</p><h2>What should we research?</h2></div><label className="field-label">Category name<input autoFocus required minLength="2" maxLength="120" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. AI meeting assistants"/></label><label className="field-label">Keywords <span className="muted-cell">Optional · comma-separated</span><input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="transcription, summaries, calendar"/></label><div className="form-actions"><button type="button" className="btn btn-quiet" onClick={()=>setShow(false)}>Cancel</button><button disabled={saving} className="btn btn-primary">{saving?'Saving…':'Save category'}</button></div></form>}
    {loading?<Loading/>:error?<ErrorState error={error} onRetry={reload}/>:<div className="category-list">{rows?.length?rows.map(c=><article className="category-row panel" key={c.id}><div className="category-icon"><Search size={18}/></div><div className="category-info"><h3>{c.name}</h3><div className="chip-row">{c.keywords?.length?c.keywords.map(k=><span className="chip" key={k}>{k}</span>):<span className="muted-cell">No keywords added</span>}</div></div><label className="switch-control"><input type="checkbox" checked={c.active} onChange={()=>toggle(c)}/><span className="switch-track"/><span className="switch-label">{c.active?'Active':'Paused'}</span></label></article>):<Empty title="No categories yet" body="Add a category to tell discovery what kinds of products to find." action={<button className="btn btn-primary btn-small" onClick={()=>setShow(true)}><Plus size={15}/> Add category</button>}/>}</div>}
    <div className="callout"><Settings2 size={17}/><p><strong>Discovery source required.</strong> Configure a Product Hunt token in the server environment before starting runs.</p></div>
  </>;
}

export function Candidates(){
  const [rows,setRows]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState('');
  async function reload(){setLoading(true);setError('');try{setRows(await getCandidates())}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{reload()},[]);const shown=(rows||[]).filter(c=>`${c.name} ${c.domain} ${c.status}`.toLowerCase().includes(query.toLowerCase()));
  return <><header className="page-heading"><div><p className="eyebrow">DISCOVERY</p><h1>Candidate pool</h1><p className="page-description">Collected products and the signals used to rank them.</p></div></header><div className="toolbar"><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search candidates" aria-label="Search candidates"/></div><span>{shown.length} candidates</span></div>{loading?<Loading/>:error?<ErrorState error={error} onRetry={reload}/>:shown.length?<div className="data-table-wrap panel"><table className="data-table"><thead><tr><th>Product</th><th>Domain</th><th>Source</th><th>Category fit</th><th>Total score</th><th>Status</th></tr></thead><tbody>{shown.map(c=><tr key={c.id}><td><a className="product-link" href={c.url} target="_blank" rel="noreferrer">{c.name}<ExternalLink size={13}/></a></td><td>{c.domain}</td><td>{c.sources?.join(', ')||'—'}</td><td>{pct(c.scores?.category_fit)}</td><td><strong>{pct(c.scores?.total)}</strong></td><td><span className={`badge badge-${c.status==='covered'?'completed':c.status==='rejected'?'failed':'pending'}`}>{c.status}</span></td></tr>)}</tbody></table></div>:<Empty title="Candidate pool is empty" body="Candidates appear here after discovery runs."/>}</>;
}
const pct=n=>Number.isFinite(Number(n))?`${Math.round(Number(n)*100)}%`:'—';

export function StyleGuide(){return <><header className="page-heading"><div><p className="eyebrow">DESIGN SYSTEM</p><h1>Style guide</h1><p className="page-description">Shared patterns and states used throughout Compare.</p></div></header><section className="section-block"><h2>Actions</h2><div className="guide-row panel"><button className="btn btn-primary"><Plus size={16}/> Primary</button><button className="btn btn-secondary">Secondary</button><button className="btn btn-quiet">Quiet</button><button className="btn btn-danger">Danger</button><button disabled className="btn btn-primary">Loading</button></div></section><section className="section-block"><h2>Statuses</h2><div className="guide-row panel">{['pending','running','completed','partial','failed'].map(x=><span key={x} className={`badge badge-${x}`}>{x}</span>)}</div></section><section className="section-block"><h2>Product colors</h2><div className="guide-row panel"><span className="product-letter letter-a">A</span><span className="color-swatch swatch-a">Product A · teal</span><span className="product-letter letter-b">B</span><span className="color-swatch swatch-b">Product B · plum</span></div></section><section className="section-block"><h2>Empty state</h2><div className="panel empty-state"><FileText/><h3>Nothing here yet</h3><p>Clear next steps make an empty view useful.</p><Link to="/" className="btn btn-secondary btn-small">Go to overview <ArrowRight size={15}/></Link></div></section></>}

export function Loading(){return <div className="loading-list" aria-label="Loading">{[1,2,3].map(n=><div key={n} className="loading-row"><i/><i/><i/></div>)}</div>}
export function Empty({title,body,action}){return <div className="empty-state"><span className="empty-icon"><FileText size={20}/></span><h3>{title}</h3><p>{body}</p>{action}</div>}
export function ErrorState({error,onRetry}){return <div className="error-state"><div><strong>We couldn’t load this view</strong><p>{error}</p></div>{onRetry&&<button className="btn btn-secondary btn-small" onClick={onRetry}>Try again</button>}</div>}
export function NotFound(){return <div className="not-found"><span className="eyebrow">404 · PAGE NOT FOUND</span><h1>This page isn’t in the research workspace.</h1><Link className="btn btn-primary" to="/">Back to overview</Link></div>}
